### ISSUE TITLE
sos is empty object

### ISSUE THREAD

**Issue by IlyasNik** [signageos/sdk#28]
Hi! Have just created test applet and got this error.
![Screenshot_2](https://user-images.githubusercontent.com/109864415/180611302-0cb0e0e4-9f10-4c10-ab1b-1d38d1ec331f.png)
![Screenshot_3](https://user-images.githubusercontent.com/109864415/180611306-a9632c68-c16f-4e8e-ad0a-474e5402fcc3.png)

**Comment by misak113** [comment]
Hi,
we are sorry. We released the new version of front-applet aka Applet SDK. Version 5.4.0 is not compatible with webpack version. So please temporarily downgrade to version 5.3.1. The 5.4.0 has been deprecated and we will release a fixed version soon.
